[project] # Project metadata
name = "apngasm-python"
description = "A nanobind API for apngasm, a tool/library for APNG assembly/disassembly."
requires-python = ">=3.7"
readme = "README.md"
license = { "file" = "LICENSE" }
authors = [{ "name" = "chaudominic", "email" = "chaudominic2@gmail.com" }]
keywords = ["apng", "png", "nanobind", "pybind11"]
classifiers = ["Topic :: Multimedia :: Graphics"]
dependencies = ["Pillow", "numpy"]
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/laggykiller/apngasm-python"
Source = "https://github.com/laggykiller/apngasm-python"
Documentation = "https://github.com/laggykiller/apngasm-python"
Tracker = "https://github.com/laggykiller/apngasm-python/issues"
repository = "https://github.com/laggykiller/apngasm-python"

[build-system] # How pip and other frontends should build this project
requires = ["py-build-cmake>=0.1.9a1", "nanobind", "nanobind-stubgen"]
build-backend = "py_build_cmake.build"

[tool.py-build-cmake.module] # Where to find the Python module to package
name = "apngasm_python"
directory = "src-python"

[tool.py-build-cmake.sdist] # What to include in source distributions
include = ["CMakeLists.txt", "cmake/*.cmake", "src/*", "*.bat", "*.sh", "apngasm/*", "zlib/*", "libpng/*", "boost/*", "nanobind/*"]

[tool.py-build-cmake.cmake] # How to build the CMake project
build_type = "Release"
source_path = "."
options = { "WITH_PY_STUBS:BOOL" = "On" }
build_args = ["-j"]
install_components = ["python_module"]

[tool.py-build-cmake.mac.cmake] # macOS-specific options
env = { "LDFLAGS" = "-L/usr/local/opt/icu4c/lib", "CPPFLAGS" = "-I/usr/local/opt/icu4c/include" } # Required for brew installed icu4c

# stubgen depends on mypy, which depends on typed-ast
# typed-ast cannot run on pypy <3.8
# https://mypy.readthedocs.io/en/stable/faq.html
# [tool.py-build-cmake.stubgen] # Whether and how to generate typed stub files