name: Build and upload to PyPI

on:
  push:
  # tags:
  #     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # release:
  #   types:
  #     - published

jobs:
  build_wheels_win_x64:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BEFORE_ALL: prepare-win.bat

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_win_x86:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_WINDOWS: x86
          CIBW_BEFORE_ALL: prepare-win.bat
          APNGASM_CROSSCOMPILE_TARGET: x86
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
  build_wheels_win_arm:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_WINDOWS: ARM64
          CIBW_BEFORE_ALL: prepare-win.bat
          APNGASM_CROSSCOMPILE_TARGET: arm64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_mac_x86:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ENVIRONMENT_MACOS: >
            _PYTHON_HOST_PLATFORM=macosx-11-x86_64
          MACOSX_DEPLOYMENT_TARGET: 11
          CIBW_BEFORE_ALL: ./prepare-mac.sh

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_mac_arm:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_MACOS: arm64
          CIBW_ENVIRONMENT_MACOS: >
            _PYTHON_HOST_PLATFORM=macosx-11-arm64
          MACOSX_DEPLOYMENT_TARGET: 11
          CIBW_BEFORE_ALL: ./prepare-mac.sh
          APNGASM_CROSSCOMPILE_TARGET: arm64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_linux_x86:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_LINUX: x86_64 i686
          CIBW_BEFORE_ALL: ./prepare-linux.sh

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_linux_arm:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_LINUX: aarch64
          CIBW_BEFORE_ALL: ./prepare-linux.sh

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
  build_wheels_ppc64le:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_LINUX: ppc64le
          CIBW_BEFORE_ALL: ./prepare-linux.sh

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
  build_wheels_s390x:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS_LINUX: s390x
          CIBW_BEFORE_ALL: ./prepare-linux.sh

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  # upload_pypi_test:
  #   needs: [build_wheels_x86, build_wheels_arm, build_wheels_ppc64le, build_wheels_s390x, build_sdist]
  #   runs-on: ubuntu-latest
  #   # upload to PyPI on every tag starting with 'v'
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         # unpacks default artifact into dist/
  #         # if `name: artifact` is omitted, the action will create extra parent dir
  #         name: artifact
  #         path: dist

  #     - uses: pypa/gh-action-pypi-publish@v1.5.0
  #       with:
  #         user: __token__
  #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
  #         repository_url: https://test.pypi.org/legacy/

  # upload_pypi:
  #   needs: [build_wheels_x86, build_wheels_arm, build_wheels_ppc64le, build_wheels_s390x, build_sdist]
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'release' && github.event.action == 'published'
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         # unpacks default artifact into dist/
  #         # if `name: artifact` is omitted, the action will create extra parent dir
  #         name: artifact
  #         path: dist

  #     - uses: pypa/gh-action-pypi-publish@v1.5.0
  #       with:
  #         user: __token__
  #         password: ${{ secrets.PYPI_API_TOKEN }}