name: Update stub

on:
  push:

jobs:
  stubgen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        submodules: recursive
    - name: Create local changes
      run: |
        pip install build
        python update_stub.py
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}